### ISSUE TITLE
IOS BUILD

### ISSUE THREAD

**Issue by toanlieu** [sonvp/flutter_zalo#1]
Ad ơi cho mình hỏi với. Flutter mình build dependencies: flutter_zalopay_sdk: ^0.1.0 nhưng mà Android mình chạy open ra app zalopay , thanh toán ok . Còn IOS mình config đầy đủ nó mở ra app ZALO  chat trên store. Ad xem giúp mình là trường hợp gì ko ạ? Thanks

**Comment by sonvp** [comment]
@toanlieu Đúng rồi bạn, nó sẻ mở zalo chat trên store, khi cài zalo chat xong, đăng nhập nó sẻ chuyển từ zalo pay, mà hiện tại example là môi trường SANDBOX nên zalo pay sẽ báo lổi. Đê test môi trường SANDBOX bạn có thể vào link dưới để cài  ZaloPay Sandbox cho ios để test.
https://docs.zalopay.vn/v1/docs/apptoapp/demo.html

**Comment by tranvietha2809** [comment]
Closing.
