### ISSUE TITLE
[Mobile - IOS] Không nhận được callback từ Zalo Pay

### ISSUE THREAD

**Issue by phuongtinhbien** [sonvp/flutter_zalo#2]
Sau khi mình thực hiện thành công thanh toán. Nhưng function listen không nhận được trạng thái thanh toán từ app Zalo Pay. Mong bạn hỗ trợ giúp mình nha

**Comment by sonvp** [comment]
Hi bạn. Hiện tại lổi này xảy do mình refactor code. Nếu cần test gấp bạn có thể checkout từ commit này "Change payOrder return type into Stream"  hoặc lấy từ flutter_zalopay_sdk: ^0.1.0 trong khi chờ mình sửa lại bug này nha.

**Comment by phuongtinhbien** [comment]
Cảm ơn bạn nha.

**Comment by sonvp** [comment]
Đã sửa.
