### ISSUE TITLE
Build apk bị lỗi

### ISSUE THREAD

**Issue by hiens** [sonvp/flutter_zalo#3]
**Mô tả**
Mình build apk thì gặp lỗi này. Build ipa và appbundle thì không lỗi.

**Tái hiện**
Chạy `flutter build apk`

**Logs**
```
[ +104 ms] FAILURE: Build failed with an
exception.
[   +6 ms] * What went wrong:
[        ] Execution failed for task
':flutter_zalopay_sdk:bundleReleaseAar'.
[        ] > Direct local .aar file dependencies
are not supported when building an AAR. The
resulting AAR would be broken because the
classes and Android resources from any local
.aar file dependencies would not be packaged in
the resulting AAR. Previous versions of the
Android Gradle Plugin produce broken AARs in
this case too (despite not throwing this error).
The following direct local .aar file
dependencies of the :flutter_zalopay_sdk project
caused this error:
/Users/tranhien/Documents/Development/flutter/.p
ub-cache/hosted/pub.dartlang.org/flutter_zalopay
_sdk-0.1.4/android/libs/zpdk-release.aar
```

**Comment by sonvp** [comment]
Hi @hiens . Bạn thử import thử bản flutter_zalopay_sdk: ^0.1.3 xem chạy được không. Mỉnh đả kiểm tra và build file apk thành công, Còn đối version 0.1.4 có vẻ do flutter 2 sdk từ google vẩn chưa ổn định nên không build apk được. Mỉnh sẻ chờ bản release flutter 2 sdk  tiếp theo của google để kiểm tra lại lôi này.

**Comment by hiens** [comment]
Mình có thử downgrade xuống 0.1.3 rồi nhưng vẫn bị lỗi này.

**Comment by sonvp** [comment]
Nếu bạn build apk trên cái demo của mình bạn có thể làm 3 bước sau
- Sử dụng flutter sdk 1.22.6
- Trong file pubspec.yaml. thay thế eviroment với đoạn bên dưới
  environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.20.0 <2.0.0"
- Trong file flutter_zalopay_sdk.dart line 15 bỏ cái  required bị lổi báo lổi đi
- Rồi chạy flutter build apk là build được

**Comment by hiens** [comment]
Project của mình khá lớn và lên null-safety 1 thời gian rồi nên giờ downgrade xuống không được.
Mình đã tạm giải quyết được bằng cách extract file arr và implement trực tiếp file classes.jar. Nhưng mình nghĩ nên publish sdk lên maven để sử dụng cho dễ.

**Comment by vukhacbiet** [comment]
> Project của mình khá lớn và lên null-safety 1 thời gian rồi nên giờ downgrade xuống không được. Mình đã tạm giải quyết được bằng cách extract file arr và implement trực tiếp file classes.jar. Nhưng mình nghĩ nên publish sdk lên maven để sử dụng cho dễ.

Bạn cho mình xin cách xử lý cụ thể được không, bên mình cũng đang gặp trường hợp tương tự, không build APK được, chỉ build được appbundle

**Comment by hiens** [comment]
> > Project của mình khá lớn và lên null-safety 1 thời gian rồi nên giờ downgrade xuống không được. Mình đã tạm giải quyết được bằng cách extract file arr và implement trực tiếp file classes.jar. Nhưng mình nghĩ nên publish sdk lên maven để sử dụng cho dễ.
> 
> Bạn cho mình xin cách xử lý cụ thể được không, bên mình cũng đang gặp trường hợp tương tự, không build APK được, chỉ build được appbundle

Bạn tìm file **zpdk-release.aar** rồi giải nén, bên trong đó sẽ có 1 file là **classes.jar**. Chỉ cần sửa lại chỗ implement thành
`implementation files('libs/zpdk-release/classes.jar')`
