### ISSUE TITLE
Cho mình hỏi khi chọn thanh toán bằng zalopay thì k thể được app zapoPay

### ISSUE THREAD

**Issue by hoangduc11** [sonvp/flutter_zalo#5]
Chào Sơn!
Cho mình hỏi khi chọn thanh toán bằng zalopay thì k thể được app zapoPay lên mình có install zaloPay về máy rồi (zaloPay Sanbox)? (Code bằng flutter sài flutter_zalopay_sdk version 1.0.4)
Mong được Sơn hỗ trợ.

**Comment by sonvp** [comment]
chào @hoangduc11 nếu bạn bị lồi nhừ #4 thì mình đã sửa và cập nhật lên pub rồi nha
