### ISSUE TITLE
Luôn luôn nhận về trạng thái FlutterZaloPayStatus.failed trên iOS

### ISSUE THREAD

**Issue by damhung-1510** [sonvp/flutter_zalo#9]

**Comment by tranvietha2809** [comment]
Bạn tham khảo: 

https://docs.zalopay.vn/v2/docs/apptoapp/demo.html

**Comment by damhung-1510** [comment]
Mình đã setup như doc của bạn mới update nhưng không hiểu sao app ko redirect sang zalopay đc và trả về fail. bạn có thể support mình chút đc ko? @tranvietha2809
